export const projects = [
  {
    title: 'Restaurant Website',
    // description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    description:"This is a design of a restaurant named ConFusion. It is my first website porject that I designed using CSS, Bootstrap and Javascript. ",  
    image: '/images/1.png',
      tags: ['JavaScript', 'Bootstrap', 'CSS'],
    source: 'https://github.com/ImranAhmed26/ConFusion/blob/main/index.html',
    visit: 'https://confusionrestro.netlify.app/',
    id: 0,
  },
  {
    title: 'Landing Page',
    description:"T I designed this landgin page as a freelance project for a client named Todd on freelancer.com.",
    image: '/images/2.png',
    tags: [ 'JavaScript', 'CSS'],
    source: 'https://github.com/ImranAhmed26/Toppi-landing-page/blob/master/index.html',
    visit: 'https://landing-page101.netlify.app/',
    id: 1,
  },
  {
    title: 'Background Color Generator',
    description: "This is one of my early project where a gradient of colors can be generated by the user. the app also provides the RGB code combinations for using elsewhere. ",
      image: '/images/3.jpg',
      tags: ['JavaScript', 'CSS'],
    source: 'https://github.com/ImranAhmed26/ZeroToMastery_BGroundGenerator/blob/master/Untitled-1.html',
    visit: 'https://bgcolor-gen.netlify.app/',
    id: 2,
  },
  {
    title: 'Color Game',
    description: "This is a color game where the user has to guess the color from the given RGB code. this app is a fun way to develop ones knowledge about RGB color codes.",
    image: '/images/4.jpg',
    tags: ['JavaScript', 'CSS'],
    source: 'https://github.com/ImranAhmed26/RBG-Color-Game/blob/master/index.html',
    visit: 'https://color-gamejs.netlify.app/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my undergraduation at AIUB', },
  { year: 2019, text: 'Started to take interest in coding', },
  { year: 2020, text: 'Completed 3 programming cources from Coursera.com', },
  { year: 2021, text: 'Graduated from AIUB', },
];